name: macOs build

on:
  push:
    branches: [ master, develop, 1.0.* ]
    tags: 1.0.*
  workflow_dispatch:
    inputs:
      manual:
        description: 'none'
        required: true
        default: ''
        type: choice
        options:
        - ''
        - warning
        - debug
    
  pull_request:
    branches: [ master, develop, 1.0.* ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        qt: ['6.4.1']

    steps:
    - uses: actions/checkout@v2
      
    - name: Installing Qt framework
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}

    - name: Running qmake
      run:  cd $GITHUB_WORKSPACE; qmake pgmodeler.pro -r PREFIX=/Applications/pgModeler.app/Contents PGSQL_INC=`/usr/local/Cellar/postgresql@15/15.2_3/bin/pg_config --includedir` PGSQL_LIB=`/usr/local/Cellar/postgresql@15/15.2_3/bin/pg_config --libdir`/libpq.dylib CONFIG+=debug
    
    - name: Building pgModeler
      run: make -j6
     
    - name: Deploying pgModeler
      run: make install
